;;; bcp-fetcher-kjva.el --- Local KJV-with-Apocrypha bundled-Bible backend -*- lexical-binding: t -*-

;;; Commentary:

;; Serves passages from `bcp-liturgy-bible-kjva.txt', a single bundled
;; KJV-with-Apocrypha file produced by `bcp-kjva-collate' from the eBible
;; eng-kjv readaloud distribution.  The KJV (1769 Blayney revision) and
;; its Apocrypha are public domain, so the bundle ships with the
;; repository and is the only fully offline English option.
;;
;; Format mirrors `bcp-liturgy-bungo-yaku.txt': one verse per line,
;;   Book Ch:V<TAB>Text
;; with SWORD canonical book names ("I Samuel", "Revelation of John").
;;
;; Book-name aliases are reused from `bcp-fetcher--book-name-aliases'.

;;; Code:

(require 'bcp-fetcher)
(require 'cl-lib)

(defcustom bcp-fetcher-kjva-file
  (expand-file-name "bcp-liturgy-bible-kjva.txt"
                    (file-name-directory
                     (or load-file-name buffer-file-name default-directory)))
  "Path to the bundled KJV-with-Apocrypha plain-text Bible.
Generated by `bcp-kjva-collate' from the eBible eng-kjv distribution."
  :type  'file
  :group 'bcp-fetcher)

(defvar bcp-fetcher--kjva-bible nil
  "Hash table mapping book names to chapter hash tables.
Each chapter hash maps chapter numbers to verse vectors (1-indexed).
Populated lazily by `bcp-fetcher--kjva-load'.")

(defun bcp-fetcher--kjva-resolve-book (name)
  "Resolve book NAME to its canonical SWORD form.
Returns NAME unchanged if it is already canonical or unrecognized."
  (or (cdr (assoc name bcp-fetcher--book-name-aliases))
      name))

(defun bcp-fetcher--kjva-load ()
  "Parse `bcp-fetcher-kjva-file' into `bcp-fetcher--kjva-bible'.
Returns the hash table, or sets the variable to \\='unavailable on error."
  (unless (file-exists-p bcp-fetcher-kjva-file)
    (setq bcp-fetcher--kjva-bible 'unavailable)
    (error "bcp-fetcher-kjva: bundled file not found: %s"
           bcp-fetcher-kjva-file))
  (let ((books (make-hash-table :test 'equal)))
    (with-temp-buffer
      (insert-file-contents bcp-fetcher-kjva-file)
      (goto-char (point-min))
      (let ((current-book nil)
            (current-ch   nil)
            (verses       nil))
        (while (not (eobp))
          (let ((line (buffer-substring-no-properties
                       (line-beginning-position) (line-end-position))))
            (when (string-match
                   "^\\(.+\\) \\([0-9]+\\):\\([0-9]+\\)\t\\(.*\\)$" line)
              (let ((book (match-string 1 line))
                    (ch   (string-to-number (match-string 2 line)))
                    (text (match-string 4 line)))
                (when (and current-book
                          (or (not (string= book current-book))
                              (/= ch current-ch)))
                  (let ((ch-table (or (gethash current-book books)
                                      (let ((h (make-hash-table :test 'eql)))
                                        (puthash current-book h books)
                                        h))))
                    (puthash current-ch (vconcat (nreverse verses)) ch-table))
                  (setq verses nil))
                (setq current-book book
                      current-ch   ch)
                (push text verses))))
          (forward-line 1))
        (when current-book
          (let ((ch-table (or (gethash current-book books)
                              (let ((h (make-hash-table :test 'eql)))
                                (puthash current-book h books)
                                h))))
            (puthash current-ch (vconcat (nreverse verses)) ch-table)))))
    (setq bcp-fetcher--kjva-bible books)))

(defun bcp-fetcher--kjva-bible ()
  "Return the KJVA Bible hash table, loading if necessary."
  (cond
   ((eq bcp-fetcher--kjva-bible 'unavailable) nil)
   (bcp-fetcher--kjva-bible)
   (t (bcp-fetcher--kjva-load))))

(defun bcp-fetcher--kjva-render-verses (book ch verses v-from v-to)
  "Render verse vector VERSES of BOOK chapter CH from V-FROM to V-TO.
Returns a propertized string or nil."
  (let* ((len   (length verses))
         (start (1- (max 1 (or v-from 1))))
         (end   (min len (or v-to len)))
         (result ""))
    (cl-loop for i from start below end
             for vnum = (1+ i)
             for text = (aref verses i)
             when (> (length text) 0) do
             (unless (string-empty-p result)
               (setq result (concat result "\n")))
             (let ((props (list 'bcp-verse vnum 'bcp-book book)))
               (when (= vnum 1)
                 (setq props (nconc props (list 'bcp-chapter ch))))
               (setq result
                     (concat result
                             (apply #'propertize (substring text 0 1) props)
                             (substring text 1)))))
    (unless (string-empty-p result) result)))

(defun bcp-fetcher--kjva-render (passage bible)
  "Render PASSAGE from KJVA BIBLE hash table as propertized text, or nil."
  (cond
   ((null bible) nil)
   ((string-match
     "^\\(.+\\) \\([0-9]+\\):\\([0-9]+\\)\\(?:-\\([0-9]+\\)\\)?$" passage)
    (let* ((book   (bcp-fetcher--kjva-resolve-book
                    (match-string 1 passage)))
           (ch     (string-to-number (match-string 2 passage)))
           (v1     (string-to-number (match-string 3 passage)))
           (v2     (when (match-string 4 passage)
                     (string-to-number (match-string 4 passage))))
           (ch-tbl (gethash book bible))
           (verses (when ch-tbl (gethash ch ch-tbl))))
      (when verses
        (bcp-fetcher--kjva-render-verses book ch verses v1 v2))))
   ((string-match "^\\(.+\\) \\([0-9]+\\)$" passage)
    (let* ((book   (bcp-fetcher--kjva-resolve-book
                    (match-string 1 passage)))
           (ch     (string-to-number (match-string 2 passage)))
           (ch-tbl (gethash book bible))
           (verses (when ch-tbl (gethash ch ch-tbl))))
      (when verses
        (bcp-fetcher--kjva-render-verses book ch verses 1 nil))))
   ((string-match "^Psalms? \\([0-9]+\\)-\\([0-9]+\\)$" passage)
    (let* ((book "Psalms")
           (n1   (string-to-number (match-string 1 passage)))
           (n2   (string-to-number (match-string 2 passage)))
           (ch-tbl (gethash book bible))
           (parts nil))
      (when ch-tbl
        (cl-loop for n from n1 to n2
                 for verses = (gethash n ch-tbl)
                 when verses do
                 (let ((rendered (bcp-fetcher--kjva-render-verses
                                 book n verses 1 nil)))
                   (when rendered (push rendered parts))))
        (when parts (mapconcat #'identity (nreverse parts) "\n\n")))))
   (t nil)))

(defun bcp-fetcher--kjva-fetch (passage _translation callback)
  "Serve PASSAGE from the local KJVA Bible and call CALLBACK with text."
  (let ((text (condition-case err
                  (bcp-fetcher--kjva-render
                   passage (bcp-fetcher--kjva-bible))
                (error
                 (message "bcp-fetcher-kjva: %s" (error-message-string err))
                 nil))))
    (when text
      (message "bcp-fetcher: %s served from local KJVA." passage))
    (funcall callback text)))

(bcp-fetcher-register-backend
 'kjva
 :name            "King James Version with Apocrypha (local)"
 :fetch-fn        #'bcp-fetcher--kjva-fetch
 :psalm-numbering 'hebrew
 :translations    '("KJVA" "KJV with Apocrypha" "King James Version with Apocrypha"))

(provide 'bcp-fetcher-kjva)
;;; bcp-fetcher-kjva.el ends here
