;;; bcp-fetcher-vulgate-bible.el --- Local Vulgata Clementina backend -*- lexical-binding: t -*-

;;; Commentary:

;; Serves passages from `bcp-liturgy-bible-vulgate.txt', the bundled
;; Bibbia Vulgata Clementina produced by `bcp-vulgate-bible-collate'
;; from the eBible latVUC distribution.  The Clementine Vulgate
;; (1592–1598) is in the public domain, so the bundle ships with the
;; repository.
;;
;; Format matches the KJVA bundle: one verse per line,
;;   Book Ch:V<TAB>Text
;; with SWORD canonical English book names.  Psalm numbering is
;; LXX/Vulgate (Psalm 50 is "Miserere").  Susanna, Bel, and the Song
;; of the Three are integrated into Daniel (chs 13, 14, and 3:24-90)
;; as in the Clementine canon.
;;
;; This backend complements the inline Vulgate *psalter* registered in
;; `bcp-fetcher.el' (which serves only Psalms with Breviary pointing
;; marks).  When the psalter layer is set, Psalms route through it;
;; this backend serves the rest of the Bible.

;;; Code:

(require 'bcp-fetcher)
(require 'cl-lib)

(defcustom bcp-fetcher-vulgate-bible-file
  (expand-file-name "bcp-liturgy-bible-vulgate.txt"
                    (file-name-directory
                     (or load-file-name buffer-file-name default-directory)))
  "Path to the bundled Vulgata Clementina plain-text Bible.
Generated by `bcp-vulgate-bible-collate' from the eBible latVUC distribution."
  :type  'file
  :group 'bcp-fetcher)

(defvar bcp-fetcher--vulgate-bible nil
  "Hash table mapping book names to chapter hash tables.
Each chapter hash maps chapter numbers to verse vectors (1-indexed).
Populated lazily by `bcp-fetcher--vulgate-bible-load'.")

(defun bcp-fetcher--vulgate-bible-resolve-book (name)
  "Resolve book NAME to its canonical SWORD form.
Tries the alias table first; if that misses, normalizes Arabic-numeral
prefixes to Roman (\"1 Samuel\" → \"I Samuel\", \"2 Kings\" → \"II Kings\")
so that lectionary-expanded full names resolve correctly.  Wraps the
regex in `save-match-data' to avoid disturbing caller match data."
  (or (cdr (assoc name bcp-fetcher--book-name-aliases))
      (save-match-data
        (cond
         ((string-match "\\`1 \\(.+\\)\\'" name)
          (concat "I "   (match-string 1 name)))
         ((string-match "\\`2 \\(.+\\)\\'" name)
          (concat "II "  (match-string 1 name)))
         ((string-match "\\`3 \\(.+\\)\\'" name)
          (concat "III " (match-string 1 name)))
         (t name)))))

(defun bcp-fetcher--vulgate-bible-load ()
  "Parse `bcp-fetcher-vulgate-bible-file' into `bcp-fetcher--vulgate-bible'.
Returns the hash table, or sets the variable to \\='unavailable on error."
  (unless (file-exists-p bcp-fetcher-vulgate-bible-file)
    (setq bcp-fetcher--vulgate-bible 'unavailable)
    (error "bcp-fetcher-vulgate-bible: bundled file not found: %s"
           bcp-fetcher-vulgate-bible-file))
  (let ((books (make-hash-table :test 'equal)))
    (with-temp-buffer
      (insert-file-contents bcp-fetcher-vulgate-bible-file)
      (goto-char (point-min))
      (let ((current-book nil)
            (current-ch   nil)
            (verses       nil))
        (while (not (eobp))
          (let ((line (buffer-substring-no-properties
                       (line-beginning-position) (line-end-position))))
            (when (string-match
                   "^\\(.+\\) \\([0-9]+\\):\\([0-9]+\\)\t\\(.*\\)$" line)
              (let ((book (match-string 1 line))
                    (ch   (string-to-number (match-string 2 line)))
                    (text (match-string 4 line)))
                (when (and current-book
                          (or (not (string= book current-book))
                              (/= ch current-ch)))
                  (let ((ch-table (or (gethash current-book books)
                                      (let ((h (make-hash-table :test 'eql)))
                                        (puthash current-book h books)
                                        h))))
                    (puthash current-ch (vconcat (nreverse verses)) ch-table))
                  (setq verses nil))
                (setq current-book book
                      current-ch   ch)
                (push text verses))))
          (forward-line 1))
        (when current-book
          (let ((ch-table (or (gethash current-book books)
                              (let ((h (make-hash-table :test 'eql)))
                                (puthash current-book h books)
                                h))))
            (puthash current-ch (vconcat (nreverse verses)) ch-table)))))
    (setq bcp-fetcher--vulgate-bible books)))

(defun bcp-fetcher--vulgate-bible ()
  "Return the Vulgate Bible hash table, loading if necessary."
  (cond
   ((eq bcp-fetcher--vulgate-bible 'unavailable) nil)
   (bcp-fetcher--vulgate-bible)
   (t (bcp-fetcher--vulgate-bible-load))))

(defun bcp-fetcher--vulgate-bible-render-verses (book ch verses v-from v-to)
  "Render verse vector VERSES of BOOK chapter CH from V-FROM to V-TO.
Returns a propertized string or nil."
  (let* ((len   (length verses))
         (start (1- (max 1 (or v-from 1))))
         (end   (min len (or v-to len)))
         (result ""))
    (cl-loop for i from start below end
             for vnum = (1+ i)
             for text = (aref verses i)
             when (> (length text) 0) do
             (unless (string-empty-p result)
               (setq result (concat result "\n")))
             (let ((props (list 'bcp-verse vnum 'bcp-book book)))
               (when (= vnum 1)
                 (setq props (nconc props (list 'bcp-chapter ch))))
               (setq result
                     (concat result
                             (apply #'propertize (substring text 0 1) props)
                             (substring text 1)))))
    (unless (string-empty-p result) result)))

(defun bcp-fetcher--vulgate-bible-render (passage bible)
  "Render PASSAGE from Vulgate BIBLE hash table as propertized text, or nil."
  (cond
   ((null bible) nil)
   ((string-match
     "^\\(.+\\) \\([0-9]+\\):\\([0-9]+\\)\\(?:-\\([0-9]+\\)\\)?$" passage)
    (let* ((book   (bcp-fetcher--vulgate-bible-resolve-book
                    (match-string 1 passage)))
           (ch     (string-to-number (match-string 2 passage)))
           (v1     (string-to-number (match-string 3 passage)))
           (v2     (when (match-string 4 passage)
                     (string-to-number (match-string 4 passage))))
           (ch-tbl (gethash book bible))
           (verses (when ch-tbl (gethash ch ch-tbl))))
      (when verses
        (bcp-fetcher--vulgate-bible-render-verses book ch verses v1 v2))))
   ((string-match "^\\(.+\\) \\([0-9]+\\)$" passage)
    (let* ((book   (bcp-fetcher--vulgate-bible-resolve-book
                    (match-string 1 passage)))
           (ch     (string-to-number (match-string 2 passage)))
           (ch-tbl (gethash book bible))
           (verses (when ch-tbl (gethash ch ch-tbl))))
      (when verses
        (bcp-fetcher--vulgate-bible-render-verses book ch verses 1 nil))))
   ;; "Book N-M" — chapter range for any book (Psalms case is a special
   ;; instance; works for "1 Samuel 24-25", "2 Kings 18-19" etc. too).
   ((string-match "^\\(.+\\) \\([0-9]+\\)-\\([0-9]+\\)$" passage)
    (let* ((book   (bcp-fetcher--vulgate-bible-resolve-book
                    (match-string 1 passage)))
           (n1     (string-to-number (match-string 2 passage)))
           (n2     (string-to-number (match-string 3 passage)))
           (ch-tbl (gethash book bible))
           (parts  nil))
      (when ch-tbl
        (cl-loop for n from n1 to n2
                 for verses = (gethash n ch-tbl)
                 when verses do
                 (let ((rendered (bcp-fetcher--vulgate-bible-render-verses
                                 book n verses 1 nil)))
                   (when rendered (push rendered parts))))
        (when parts (mapconcat #'identity (nreverse parts) "\n\n")))))
   (t nil)))

(defun bcp-fetcher--vulgate-bible-fetch (passage _translation callback)
  "Serve PASSAGE from the local Vulgate Bible and call CALLBACK with text."
  (let ((text (condition-case err
                  (bcp-fetcher--vulgate-bible-render
                   passage (bcp-fetcher--vulgate-bible))
                (error
                 (message "bcp-fetcher-vulgate-bible: %s"
                          (error-message-string err))
                 nil))))
    (when text
      (message "bcp-fetcher: %s served from local Vulgate." passage))
    (funcall callback text)))

(bcp-fetcher-register-backend
 'vulgate-bible
 :name            "Vulgata Clementina (local)"
 :fetch-fn        #'bcp-fetcher--vulgate-bible-fetch
 :psalm-numbering 'lxx
 :translations    '("Vulgate" "Latin"))

(provide 'bcp-fetcher-vulgate-bible)
;;; bcp-fetcher-vulgate-bible.el ends here
