;;; bcp-bungo-point.el --- Auto-point Bungo-yaku psalter from Coverdale -*- lexical-binding: t -*-

;; One-time utility to fill out bcp-liturgy-psalter-bungo-yaku.txt
;; with auto-pointed psalms.  Hand-pointed verses already in the file
;; are preserved verbatim; missing verses are generated by syncing
;; mediant placement to the parallel Coverdale verse.
;;
;; Strategy: for each Bungo verse, locate Coverdale's ＊ position as
;; a fraction of its visible text, then place ＊ at the same
;; fractional position in the Bungo verse.  Where the Bungo source
;; has spaces (phrase boundaries from the digital edition), prefer
;; the space closest to the proportional target; otherwise insert at
;; the proportional position.
;;
;; The flex mark (†) is not produced automatically — it is a
;; judgment call requiring Japanese fluency.  Long verses simply
;; receive a single ＊.

;;; Code:

(defvar bcp-bungo-point-source-file
  (expand-file-name "bcp-liturgy-bungo-yaku.txt"
                    (file-name-directory (or load-file-name buffer-file-name)))
  "Source file: full Bungo-yaku Bible.")

(defvar bcp-bungo-point-coverdale-file
  (expand-file-name "bcp-liturgy-psalter-coverdale.txt"
                    (file-name-directory (or load-file-name buffer-file-name)))
  "Coverdale psalter, used to derive mediant placement fractions.")

(defvar bcp-bungo-point-target-file
  (expand-file-name "bcp-liturgy-psalter-bungo-yaku.txt"
                    (file-name-directory (or load-file-name buffer-file-name)))
  "Bungo-yaku psalter file.  Read for existing hand-pointing and overwritten.")

;; --- Coverdale parsing -------------------------------------------------

(defun bcp-bungo-point--parse-coverdale ()
  "Return hashtable mapping (psalm . verse) -> mediant fraction in [0,1]."
  (let ((tbl (make-hash-table :test 'equal))
        (psalm nil))
    (with-temp-buffer
      (insert-file-contents bcp-bungo-point-coverdale-file)
      (goto-char (point-min))
      (while (not (eobp))
        (let ((line (buffer-substring-no-properties
                     (line-beginning-position) (line-end-position))))
          (cond
           ((string-match "^Psalm \\([0-9]+\\)$" line)
            (setq psalm (string-to-number (match-string 1 line))))
           ((and psalm (string-match "^\\([0-9]+\\)\t\\(.*\\)$" line))
            (let* ((v (string-to-number (match-string 1 line)))
                   (text (match-string 2 line))
                   (sep (string-match " \\* +" text)))
              (when sep
                (let* ((before (string-trim (substring text 0 sep)))
                       (after (string-trim (substring text (match-end 0))))
                       (lb (length before))
                       (la (length after))
                       (total (+ lb la)))
                  (when (> total 0)
                    (puthash (cons psalm v)
                             (/ (float lb) total)
                             tbl))))))))
        (forward-line 1)))
    tbl))

;; --- Bungo source parsing ----------------------------------------------

(defun bcp-bungo-point--parse-bungo-source ()
  "Return hashtable mapping (psalm . verse) -> source text.
Strips leading `○' from Ps 119 letter labels."
  (let ((tbl (make-hash-table :test 'equal)))
    (with-temp-buffer
      (insert-file-contents bcp-bungo-point-source-file)
      (goto-char (point-min))
      (while (re-search-forward
              "^Psalms \\([0-9]+\\):\\([0-9]+\\)\t\\(.*\\)$" nil t)
        (let ((p (string-to-number (match-string 1)))
              (v (string-to-number (match-string 2)))
              (text (match-string 3)))
          ;; Strip leading "○" used in source for Ps 119 letter labels
          (when (string-prefix-p "○" text)
            (setq text (substring text 1)))
          (puthash (cons p v) text tbl))))
    tbl))

;; --- Existing pilot parsing --------------------------------------------

(defun bcp-bungo-point--parse-pilot ()
  "Return hashtable of already-pointed verses: (psalm . verse) -> text.
A verse counts as already-pointed if it contains ＊ or †."
  (let ((tbl (make-hash-table :test 'equal))
        (psalm nil))
    (when (file-exists-p bcp-bungo-point-target-file)
      (with-temp-buffer
        (insert-file-contents bcp-bungo-point-target-file)
        (goto-char (point-min))
        (while (not (eobp))
          (let ((line (buffer-substring-no-properties
                       (line-beginning-position) (line-end-position))))
            (cond
             ((string-match "^Psalm \\([0-9]+\\)$" line)
              (setq psalm (string-to-number (match-string 1 line))))
             ((and psalm (string-match "^\\([0-9]+\\)\t\\(.*\\)$" line))
              (let ((v (string-to-number (match-string 1 line)))
                    (text (match-string 2 line)))
                (when (or (string-search "＊" text)
                          (string-search "†" text))
                  (puthash (cons psalm v) text tbl))))))
          (forward-line 1))))
    tbl))

;; --- Mediant insertion -------------------------------------------------

(defun bcp-bungo-point--strip-ruby (text)
  "Strip ruby `《...》' from TEXT.
Return cons (VISIBLE . POSMAP) where POSMAP is a vector of length
\(1+ (length VISIBLE)) mapping each visible-char index to the
corresponding original-text index, with a sentinel at the end."
  (let* ((len (length text))
         (visible-chars '())
         (posmap-list '())
         (in-ruby nil))
    (dotimes (i len)
      (let ((c (aref text i)))
        (cond
         ((eq c ?《) (setq in-ruby t))
         ((eq c ?》) (setq in-ruby nil))
         (in-ruby nil)
         (t
          (push c visible-chars)
          (push i posmap-list)))))
    ;; Sentinel: end-of-text position
    (push len posmap-list)
    (cons (concat (nreverse visible-chars))
          (apply #'vector (nreverse posmap-list)))))

(defconst bcp-bungo-point--leading-particles
  '(?に ?を ?は ?の ?へ ?と ?も ?や ?ぞ ?か ?が ?で ?ば)
  "Hiragana characters that should NOT start the post-mediant half.
A break placed immediately before one of these would orphan the
particle from the preceding noun (e.g. `汝 ＊ により' is wrong — the
`に' belongs with `汝').")

(defconst bcp-bungo-point--trailing-connectives
  '(?の ?へ ?と ?が)
  "Hiragana particles that should NOT end the pre-mediant half.
A break placed immediately after one of these would orphan a
modifier from the following noun (e.g. `なんぢの ＊ 口' is wrong —
the genitive `の' belongs with the noun that follows).")

(defun bcp-bungo-point--kanji-p (c)
  "Non-nil if C is a CJK ideograph (kanji)."
  (or (and (>= c #x4E00) (<= c #x9FFF))   ; CJK Unified Ideographs
      (and (>= c #x3400) (<= c #x4DBF))   ; CJK Extension A
      (and (>= c #xF900) (<= c #xFAFF)))) ; CJK Compatibility

(defun bcp-bungo-point--kana-p (c)
  "Non-nil if C is hiragana or katakana."
  (or (and (>= c #x3040) (<= c #x309F))   ; Hiragana
      (and (>= c #x30A0) (<= c #x30FF)))) ; Katakana

(defun bcp-bungo-point--break-quality (visible i)
  "Score the break-quality of inserting ＊ at visible position I.
A higher score is a better break.  Strong signals:
  - existing space (rank 100)
  - kana followed by kanji, not orphaning a particle (rank 50)
  - kana followed by kana, not orphaning a particle (rank 20)
Weak signals (negative): orphaning a leading particle."
  (cond
   ((or (<= i 0) (>= i (length visible))) -1000)
   ((eq (aref visible (1- i)) ?\s) 100)
   ((eq (aref visible i) ?\s) 100)
   ((memq (aref visible i) bcp-bungo-point--leading-particles) -50)
   ((memq (aref visible (1- i)) bcp-bungo-point--trailing-connectives) -40)
   (t
    (let ((prev (aref visible (1- i)))
          (curr (aref visible i)))
      (cond
       ((and (bcp-bungo-point--kana-p prev)
             (bcp-bungo-point--kanji-p curr)) 50)
       ((and (bcp-bungo-point--kana-p prev)
             (bcp-bungo-point--kana-p curr)) 20)
       ((bcp-bungo-point--kanji-p prev) 10)
       (t 0))))))

(defun bcp-bungo-point--insert-mediant (text frac)
  "Insert ＊ into TEXT at fractional visible position FRAC.
Searches a window around the proportional target for the highest-
scoring break point per `bcp-bungo-point--break-quality'."
  (let* ((stripped (bcp-bungo-point--strip-ruby text))
         (visible (car stripped))
         (posmap (cdr stripped))
         (vlen (length visible))
         (target (max 1 (min (1- vlen) (round (* frac vlen)))))
         ;; Search window: ±25% of verse length, but at least ±3 chars
         (window (max 3 (round (* 0.25 vlen))))
         (lo (max 1 (- target window)))
         (hi (min (1- vlen) (+ target window)))
         (best-i target)
         (best-score -2000))
    (cl-loop for i from lo to hi do
             (let* ((q (bcp-bungo-point--break-quality visible i))
                    ;; Penalize distance from target (1 point per char)
                    (score (- q (abs (- i target)))))
               (when (> score best-score)
                 (setq best-score score
                       best-i i))))
    (let* ((orig (aref posmap best-i))
           (before (substring text 0 orig))
           (after (substring text orig)))
      (concat (string-trim-right before) " ＊ " (string-trim-left after)))))

;; --- Driver ------------------------------------------------------------

(defvar bcp-bungo-point-header
  ";; 文語訳詩篇 — Bungo-yaku Psalter, pointed for chant.\n\
;; Pss 1-55 and Ps 119:1-8: hand-pointed.\n\
;; Pss 56-150 and Ps 119:9-176: auto-pointed via Coverdale-mediant sync.\n\
;; Versification: Hebrew (KJV), matching bcp-liturgy-bungo-yaku.txt.\n\
;; Pointing: ＊ = mediant; † = flex (only on hand-pointed verses).\n\
;; Furigana preserved from source as kanji《reading》.\n\
;; Regenerate with `M-x bcp-bungo-point'.\n"
  "Header comment for the output file.")

(defun bcp-bungo-point--max-verse (source-tbl psalm)
  "Return the highest verse number for PSALM in SOURCE-TBL."
  (let ((max-v 0))
    (maphash (lambda (k _v)
               (when (and (eq (car k) psalm)
                          (> (cdr k) max-v))
                 (setq max-v (cdr k))))
             source-tbl)
    max-v))

(defun bcp-bungo-point ()
  "Regenerate the Bungo-yaku psalter, preserving existing hand-pointing.
Reads the Bungo source and Coverdale psalter, fills missing verses
via Coverdale-mediant proportional sync, and writes
`bcp-bungo-point-target-file' with all 150 psalms in canonical order."
  (interactive)
  (let* ((coverdale (bcp-bungo-point--parse-coverdale))
         (source    (bcp-bungo-point--parse-bungo-source))
         (pilot     (bcp-bungo-point--parse-pilot))
         (generated 0)
         (preserved 0))
    (with-temp-file bcp-bungo-point-target-file
      ;; The header comment lines start with ";;" but the original
      ;; pilot used ";".  We normalize to ";" to match the existing
      ;; convention parsed by no one but human readers.
      (insert (replace-regexp-in-string "^;;" ";" bcp-bungo-point-header))
      (insert "\n")
      (dotimes (i 150)
        (let* ((p (1+ i))
               (max-v (bcp-bungo-point--max-verse source p)))
          (when (> max-v 0)
            (insert (format "Psalm %d\n" p))
            (dotimes (j max-v)
              (let* ((v (1+ j))
                     (key (cons p v))
                     (existing (gethash key pilot))
                     (out-text
                      (cond
                       (existing
                        (cl-incf preserved)
                        existing)
                       (t
                        (cl-incf generated)
                        (let ((src (gethash key source))
                              (frac (gethash key coverdale)))
                          (cond
                           ((null src) "")    ; gap in source
                           ((null frac) src)  ; no Coverdale match: emit unpointed
                           (t (bcp-bungo-point--insert-mediant src frac))))))))
                (when (and out-text (not (string-empty-p out-text)))
                  (insert (format "%d\t%s\n" v out-text)))))
            (insert "\n")))))
    (message "Bungo psalter: %d preserved (hand-pointed), %d generated (auto-pointed)"
             preserved generated)))

(provide 'bcp-bungo-point)
;;; bcp-bungo-point.el ends here
